(()=>{'use strict';
// AMP Lab Respec Rebuild — Step 3 v2
// Concrete-demand projection + exact solver-state dedupe + safe path-row dominance.
// No Top-N, percentile cutoff, score quota, or random sampling.
const round6=x=>Math.round((Number(x)||0)*1e6)/1e6;
const stable=x=>{if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(stable).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}'};
function enrich(arr){const d=new Set(arr||[]);for(const x0 of [...d]){const x=String(x0);if(x.startsWith('DAMAGE:'))d.add('DAMAGE_TYPE:'+x.slice(7));if(x.startsWith('CAN_DEAL_')){const t=x.slice(9).toLowerCase();d.add('DAMAGE_TYPE:'+t.charAt(0).toUpperCase()+t.slice(1))}if(x==='RAGE')d.add('RESOURCE:Rage');if(x==='WILD_SHAPE')d.add('RESOURCE:WildShape');if(x==='CHANNEL_DIVINITY')d.add('RESOURCE:ChannelDivinity');if(x==='SORCERY_POINTS')d.add('RESOURCE:SorceryPoint');if(x==='PACT_MAGIC')d.add('RESOURCE:WarlockSpellSlot');if(x==='SPELLCASTING'||/_CASTING$/.test(x))d.add('CAPABILITY:SPELLCASTING');if(x==='CAN_HEAL')d.add('CAPABILITY:HEALING')}return d}
function reqKey(r0){const r=r0?.requirement||r0||{},k=String(r.kind||''),v=String(r.value||'');return k&&v?`${k}:${v}`:''}
function demandUniverse(ctx){const req=new Set,prof=new Set;for(const p of ctx?.owned_item_profiles||[]){if(!p||p.nonEquippable||p.optimizer_excluded)continue;const pg=String(p?.equip_requirements?.proficiency_group||'').trim();if(pg)for(const x of pg.split(';'))if(x.trim())prof.add(x.trim());for(const pay of p?.payoffs||[]){for(const r of pay?.external_requirements||[]){const k=reqKey(r);if(k)req.add(k)}for(const r of pay?.guards||[]){const k=reqKey(r);if(k)req.add(k)}}}for(const [fam,rows] of Object.entries(ctx?.matrix||{})){if(ctx?.owned_orbs&&!(fam in ctx.owned_orbs))continue;for(const row of rows||[])for(const path of row?.paths||[])for(const r of path?.requirements||[]){const k=reqKey(r);if(k)req.add(k)}}return {req,prof}}
function projectedState(c,demand){const g0=enrich(c?.profile?.guaranteed_capabilities),s0=enrich(c?.profile?.selectable_capabilities);const g=[...g0].filter(x=>demand.req.has(x)).sort(),s=[...s0].filter(x=>demand.req.has(x)).sort(),p=(c?.profile?.proficiencies||[]).map(String).filter(x=>demand.prof.has(x)).sort();return {g,s,p,dual:(c?.profile?.guaranteed_capabilities||[]).includes('PASSIVE:DualWielder')}}
function identityCaches(matrix,ownedOrbs){const fams=Object.keys(matrix||{}).filter(f=>!ownedOrbs||f in ownedOrbs).sort(),rowBy=new Map,owners=new Set;for(const fam of fams)for(const row of matrix?.[fam]||[]){owners.add(row.owner);rowBy.set(`${fam}|${row.owner}`,row)}const matrixId=new Map,pathId=new Map,matSigToId=new Map,pathSigToId=new Map;for(const owner of [...owners].sort()){const full=[],paths=[];for(const fam of fams){const row=rowBy.get(`${fam}|${owner}`)||null;full.push(row?Object.fromEntries(Object.entries(row).filter(([k])=>k!=='owner')):null);paths.push(row?.paths||null)}const ms=stable(full),ps=stable(paths);if(!matSigToId.has(ms))matSigToId.set(ms,'M'+matSigToId.size);if(!pathSigToId.has(ps))pathSigToId.set(ps,'P'+pathSigToId.size);matrixId.set(owner,matSigToId.get(ms));pathId.set(owner,pathSigToId.get(ps))}return {fams,rowBy,matrixId,pathId,matrix_signature_classes:matSigToId.size,path_signature_classes:pathSigToId.size}}
function identityLevels(c){const out=[];for(const z of c?.components||[]){const id=String(z.identity||z.subclass||z.class||'');if(!id)continue;out.push([id,Number(z.levels)||0])}return out}
function exactKey(c,st,cache){const parts=identityLevels(c).map(([id,lv])=>[cache.matrixId.get(id)||`OWNER:${id}`,lv]);const by={};for(const [sig,lv] of parts)(by[sig]??=[]).push(lv);const weights=[];for(const sig of Object.keys(by).sort()){const a=by[sig];weights.push([sig,a.length>1?Math.max(...a):a[0]])}return stable([weights,st.g,st.s,st.p,st.dual])}
function pathGroupKey(c,st,cache){const sigs=identityLevels(c).map(([id])=>cache.pathId.get(id)||`OWNER:${id}`).sort();return stable([sigs,st.g,st.s,st.p,st.dual])}
function rowTerm(row,w){if(!row)return -1e30;return round6((Number(row.orb_fit_score)||0)*.50+(Number(row.activation_score)||0)*.16+((Number(row.identity_score)||0)*.28+Math.max(0,Number(row.subclass_delta)||0)*.06)*w)}
function pathRowVector(c,cache){const members=new Map;for(const [id,lv] of identityLevels(c)){const ps=cache.pathId.get(id)||`OWNER:${id}`;(members.get(ps)||members.set(ps,[]).get(ps)).push([id,lv/Math.max(1,Number(c?.profile?.level)||12)])}const out=[];for(const ps of [...members.keys()].sort())for(const fam of cache.fams){let best=-1e30;for(const [id,w] of members.get(ps)){best=Math.max(best,rowTerm(cache.rowBy.get(`${fam}|${id}`),w))}out.push(best)}return out}
function vectorDominates(a,b){let strict=false;if(a.length!==b.length)return false;for(let i=0;i<a.length;i++){if(a[i]<b[i]-1e-9)return false;if(a[i]>b[i]+1e-9)strict=true}return strict}
function concreteRelevant(c,st,ctx,cache){if(st.g.length||st.s.length||st.p.length||st.dual)return true;for(const [id] of identityLevels(c))for(const fam of cache.fams){const row=cache.rowBy.get(`${fam}|${id}`);if(row&&Number(row.orb_fit_score)>0)return true}return false}
function filter(candidates,ctx={}){const currentKey=String(ctx.current_key||''),demand=demandUniverse(ctx),cache=identityCaches(ctx.matrix||{},ctx.owned_orbs||null),audit=[],relevant=[],singles=[];for(const c of candidates||[]){const st=projectedState(c,demand);c.step3v2_state=st;if(c.key===currentKey||concreteRelevant(c,st,ctx,cache)){relevant.push(c);if(c.kind!=='MULTICLASS')singles.push(c)}else audit.push({key:c.key,stage:'RELEVANT',reason:'NO_CONCRETE_OWNED_DEMAND_OR_ORB_ROW'})}
// Exact solver-state equivalence. Prefer the current path; otherwise deterministic lexical key.
const exact=new Map;for(const c of relevant){if(c.kind!=='MULTICLASS')continue;const k=exactKey(c,c.step3v2_state,cache),old=exact.get(k);if(!old||c.key===currentKey||(old.key!==currentKey&&String(c.key).localeCompare(String(old.key))<0)){if(old)audit.push({key:old.key,stage:'EFFICIENT',reason:'EXACT_SOLVER_STATE_EQUIVALENT',kept:c.key});exact.set(k,c)}else audit.push({key:c.key,stage:'EFFICIENT',reason:'EXACT_SOLVER_STATE_EQUIVALENT',kept:old.key})}
const deduped=[...singles,...exact.values()],groups=new Map;for(const c of deduped){if(c.kind!=='MULTICLASS')continue;const k=pathGroupKey(c,c.step3v2_state,cache);(groups.get(k)||groups.set(k,[]).get(k)).push({c,v:pathRowVector(c,cache)})}
const dominated=new Set;for(const arr of groups.values()){if(arr.length<2)continue;for(let i=0;i<arr.length;i++){const bi=arr[i];if(bi.c.key===currentKey)continue;for(let j=0;j<arr.length;j++){if(i===j)continue;const aj=arr[j];if(vectorDominates(aj.v,bi.v)){dominated.add(bi.c.key);audit.push({key:bi.c.key,stage:'EFFICIENT',reason:'SAME_MECHANICS_PATH_ROW_DOMINATED',kept:aj.c.key});break}}}}
const efficient=deduped.filter(c=>!dominated.has(c.key));const supported=[];for(const c of efficient){if(c.key===currentKey||concreteRelevant(c,c.step3v2_state,ctx,cache))supported.push(c);else audit.push({key:c.key,stage:'INVENTORY_SUPPORTED',reason:'NO_CONCRETE_SUPPORT_AFTER_PRUNING'})}supported.sort((a,b)=>String(a.key).localeCompare(String(b.key)));return {status:'PASS',version:'amp-respec-step3-concrete-dominance-v2',input:(candidates||[]).length,relevant:relevant.length,efficient:efficient.length,inventory_supported:supported.length,demand:{requirement_keys:demand.req.size,proficiency_groups:demand.prof.size,matrix_signature_classes:cache.matrix_signature_classes,path_signature_classes:cache.path_signature_classes},candidates:supported,audit}}
const API={version:'amp-respec-step3-concrete-dominance-v2',filter,demandUniverse,projectedState};if(typeof module!=='undefined'&&module.exports)module.exports=API;else self.AMPRespecCandidateFilter=API;
})();
