const fs=require('fs');
const solver=require('/mnt/data/v8_solver_runtime_optimized_internals5.js'),I=solver._internals;
const coach=require('/mnt/data/v8_coach_runtime_export.js');
const data=JSON.parse(fs.readFileSync('/mnt/data/solver_data_extracted.json'));
const rawSnap=JSON.parse(fs.readFileSync('/mnt/data/QuickSave_91_direct_snapshot.json'));
const cap=JSON.parse(fs.readFileSync('/mnt/data/work_respec/capability_graph_extracted.json'));
const cat=JSON.parse(fs.readFileSync('/mnt/data/AMP_Respec_Rebuild_Step4_Respec_Profile_Catalog_v1/STEP4_RESPEC_PROFILE_CATALOG.json'));
const insts=solver.normalize(rawSnap,data).instances, items=data.items, bridges=data.bridges;
const GENERIC=new Set(['ATTACK','WEAPON_ATTACK','MELEE_ATTACK','MELEE_WEAPON_ATTACK','RANGED_ATTACK','RANGED_WEAPON_ATTACK','ON_ATTACK','ON_DAMAGE','ON_DAMAGED','CRITICAL_HIT','KILL','IN_COMBAT','ON_STATUS_APPLIED','ON_STATUS_REMOVED']);
const round3=x=>Math.round((Number(x)||0)*1000)/1000;
// Exact compiled item scorer. Validated separately against frozen itemValue.
const compiled={};
for(const [sid,p] of Object.entries(items)){
 const deep=(p.deep_effects||[]).map(e=>({req:(e.requirements||[]).filter(r=>!(r.kind==='TARGET_STATE'&&r.value==='CLEAR')).map(r=>`${r.kind}:${r.value}`),any:(e.any_requirements||[]).filter(r=>!(r.kind==='TARGET_STATE'&&r.value==='CLEAR')).map(r=>`${r.kind}:${r.value}`),anyAuto:(e.any_requirements||[]).some(r=>r.kind==='TARGET_STATE'&&r.value==='CLEAR'),v:(Number(e.score)||0)*(Number(e.activity_factor)||1)}));
 function compileTyped(rows,w){const groups=new Map;for(const e of rows||[]){const sig=solver.effectReqSignature(e);if(!groups.has(sig))groups.set(sig,[]);groups.get(sig).push(e)}const out=[];for(const es of groups.values()){const rs=es[0]?.external_requirements||es[0]?.guards||[];let invalid=false;const req=[];for(const r of rs){if(r?.kind==='TRIGGER'&&GENERIC.has(r.value))continue;const k=solver.reqKey(r);if(!k){invalid=true;break}req.push(k)}out.push({req,invalid,v:w*Math.min(1.75,1+.25*(es.length-1))})}return out}
 compiled[sid]={struct:solver.structuralScore(p,true),deep,pay:compileTyped(p.payoffs,6),amp:compileTyped(p.amplifiers,6.5),caps:[...solver.itemCaps(p)],coverage:[...I.coverage(p)]};
}
const bridgeScore={}; for(const fam of Object.keys(bridges||{})){bridgeScore[fam]={};for(const sid of Object.keys(items)){const [v]=I.bridge(fam,sid,bridges);if(v)bridgeScore[fam][sid]=v}}
function typedActiveGroups(groups,caps){let s=0;for(const g of groups){if(g.invalid)continue;let ok=true;for(const k of g.req)if(!caps.has(k)){ok=false;break}if(ok)s+=g.v}return s}
function deepScore(c,caps){let pos=0,neg=0;for(const e of c.deep){let ok=true;for(const k of e.req)if(!caps.has(k)){ok=false;break}if(!ok)continue;if(e.any.length&&!e.anyAuto&&!e.any.some(k=>caps.has(k)))continue;if(e.v>=0)pos+=e.v;else neg+=e.v}return round3(Math.min(22,pos)+Math.max(-12,neg))}
function activeTypedCompiled(c,caps){return round3(Math.min(22,typedActiveGroups(c.pay,caps))+Math.min(18,typedActiveGroups(c.amp,caps)))}
function fastScore(id,fam,gear,ch,baseCaps){const ins=insts[id],sid=ins.stats_id,c=compiled[sid];const caps=new Set(baseCaps);for(const gi of gear)for(const x of compiled[insts[gi].stats_id].caps)caps.add(x);const evalCaps=new Set(caps);for(const x of c.caps)evalCaps.add(x);let score=c.struct+deepScore(c,evalCaps)+activeTypedCompiled(c,evalCaps)+(bridgeScore[fam]?.[sid]||0);
 const nc=c.caps.filter(x=>!caps.has(x));if(nc.length){const after=new Set(caps);for(const x of nc)after.add(x);const closedSigs=new Set;for(const gi of gear){const gp=items[insts[gi].stats_id];for(const e of [...(gp.payoffs||[]),...(gp.amplifiers||[])])if(!solver.effectActive(e,caps)&&solver.effectActive(e,after))closedSigs.add(`${insts[gi].stats_id}|${solver.effectReqSignature(e)}`)}if(closedSigs.size)score+=Math.min(20,7*closedSigs.size)}
 if((ch.coverage_needs||[]).length){const needs=new Set(ch.coverage_needs||[]),provided=new Set;for(const gi of gear)for(const x of compiled[insts[gi].stats_id].coverage)provided.add(x);const ncov=c.coverage.filter(x=>needs.has(x)&&!provided.has(x));score+=75*ncov.length}
 if(ins.equipped)score+=.4;score+=.8;return round3(score)}
function preindexFast(chars,ordered){const out=[];for(let ci=0;ci<chars.length;ci++){const ch=chars[ci],c=ordered[ci],ep=I.effProfs(ch,data.profs),dual=!!ch.dual_wielder,core=[...c.gear_instance_ids],base=new Set(c.base_caps||[]),by={};for(const [id,ins] of Object.entries(insts)){if(core.includes(id)||I.orbInfo(ins.stats_id))continue;const p=items[ins.stats_id];if(!p||p.nonEquippable||p.optimizer_excluded||!I.profLegal(p,ep)||!I.slotsLegal([...core,id],insts,items,dual))continue;const v=fastScore(id,c.orb_family,core,ch,base),bv=bridgeScore[c.orb_family]?.[ins.stats_id]||0,cov=compiled[ins.stats_id].coverage.some(x=>(ch.coverage_needs||[]).includes(x));if(v<=0&&!bv&&!cov)continue;(by[I.normSlot(p)]??=[]).push([v,id])}let pool=[];for(const [sl,rows] of Object.entries(by)){rows.sort((a,b)=>b[0]-a[0]||String(b[1]).localeCompare(String(a[1])));pool.push(...rows.slice(0,['WEAPON','RING'].includes(sl)?12:8))}pool.sort((a,b)=>b[0]-a[0]||String(b[1]).localeCompare(String(a[1])));const winners=new Set(Object.values(by).filter(a=>a.length).map(a=>a[0][1])),chosen=[],seen=new Set;for(const r of pool)if(!seen.has(r[1])&&(chosen.length<56||winners.has(r[1]))){chosen.push(r);seen.add(r[1])}out.push(chosen)}return out}
function fullComboFast(sel,chars,pools){const si=I.shareIndex(data.matrix),cb=Object.fromEntries(sel.map(c=>[c.character_id,c])),ordered=chars.map(c=>cb[c.id]),ig=ordered.map(c=>[...c.gear_instance_ids]),iu=new Set(ig.flat()),base=ordered.reduce((n,c)=>n+c.score,0);let beam=[[base,ig,iu]],terms=[],seen=new Set([JSON.stringify(ig.map(g=>[...g].sort()))]);for(let step=0;step<10;step++){const nxt=[];for(const [score,gears,used] of beam){terms.push([score,gears,used]);const opts=[];for(let ci=0;ci<chars.length;ci++){const ch=chars[ci],c=ordered[ci],dual=!!ch.dual_wielder,gear=gears[ci],bc=new Set(c.base_caps||[]);for(const [,id] of pools[ci]){if(used.has(id)||!I.slotsLegal([...gear,id],insts,items,dual))continue;const v=fastScore(id,c.orb_family,gear,ch,bc);if(v>0)opts.push([v,ci,id])}}opts.sort((a,b)=>b[0]-a[0]||String(b[2]).localeCompare(String(a[2])));for(const [v,ci,id] of opts.slice(0,6)){const ng=gears.map(g=>[...g]);ng[ci].push(id);const key=JSON.stringify(ng.map(g=>[...g].sort()));if(seen.has(key))continue;seen.add(key);const nu=new Set(used);nu.add(id);nxt.push([score+v,ng,nu])}}if(!nxt.length)break;nxt.sort((a,b)=>b[0]-a[0]);beam=nxt.slice(0,3)}terms.push(...beam);const valid=[];for(const [score,gears,used] of terms){const providers=chars.map((ch,i)=>I.shareables(ch,gears[i],insts,items,si));let ok=true;for(let i=0;i<ordered.length;i++){const oth=new Set;providers.forEach((s,j)=>{if(j!==i)for(const x of s)oth.add(x)});if((ordered[i].party_requirement_keys||[]).some(x=>!oth.has(x))){ok=false;break}}if(!ok)continue;let pen=0;for(let i=0;i<chars.length;i++){const cov=new Set;for(const id of gears[i])for(const x of compiled[insts[id].stats_id].coverage)cov.add(x);const needs=new Set(chars[i].coverage_needs||[]);pen+=120*[...needs].filter(x=>!cov.has(x)).length}valid.push([score-pen,gears,used])}valid.sort((a,b)=>b[0]-a[0]);return valid[0]||null}
function postfillFast(best,chars,ordered){let [score,gears,used]=best;gears=gears.map(g=>[...g]);used=new Set(used);while(true){const moves=[];for(let ci=0;ci<chars.length;ci++){const ch=chars[ci],c=ordered[ci],ep=I.effProfs(ch,data.profs),dual=!!ch.dual_wielder,d=I.deficits(gears[ci],insts,items),bc=new Set(c.base_caps||[]);if(!Object.values(d).some(Boolean))continue;const legal=[],altCount={};for(const [id,ins] of Object.entries(insts)){if(used.has(id)||I.orbInfo(ins.stats_id))continue;const p=items[ins.stats_id];if(!p||p.nonEquippable||p.optimizer_excluded||!I.profLegal(p,ep))continue;const sl=I.normSlot(p);if(!d[sl]||!I.slotsLegal([...gears[ci],id],insts,items,dual))continue;legal.push([id,sl]);altCount[sl]=(altCount[sl]||0)+1}for(const [id,sl] of legal){const v=fastScore(id,c.orb_family,gears[ci],ch,bc);if(v<=0)continue;const alt=Math.max(0,(altCount[sl]||1)-1);moves.push([v+.25/(1+alt),v,ci,id,sl])}}if(!moves.length)break;moves.sort((a,b)=>b[0]-a[0]||b[1]-a[1]||String(b[3]).localeCompare(String(a[3])));const [,v,ci,id]=moves[0];gears[ci].push(id);used.add(id);score+=v}return [score,gears,used]}
function allocateFast(snapshot){const n=solver.normalize(snapshot,data),chars=n.characters;if(chars.length!==4)return {status:'NO_SOLUTION'};const pidx=I.producerIndex(insts,items),lists=chars.map(c=>I.buildCore(c,data,insts,pidx));if(lists.some(x=>!x.length))return {status:'NO_SOLUTION'};const combos=I.topCombos(lists,3);let best=null,bsel=null;for(const [,sel] of combos){const cb=Object.fromEntries(sel.map(c=>[c.character_id,c])),ordered=chars.map(c=>cb[c.id]),pools=preindexFast(chars,ordered),x=fullComboFast(sel,chars,pools);if(x&&(!best||x[0]>best[0])){best=x;bsel=sel}}if(!best)return {status:'NO_SOLUTION'};const cb=Object.fromEntries(bsel.map(c=>[c.character_id,c])),ordered=chars.map(c=>cb[c.id]);const pf=postfillFast(best,chars,ordered);const score=round3(pf[0]),gears=pf[1];const builds=[];for(let ci=0;ci<chars.length;ci++){const ch=chars[ci],c=ordered[ci],seq=[...c.gear_instance_ids],cs=new Set(seq);let bs=Number(c.score)||0;for(const id of gears[ci])if(!cs.has(id)){bs+=fastScore(id,c.orb_family,seq,ch,new Set(c.base_caps||[]));seq.push(id)}builds.push({character_name:ch.name,identity:c.identity,orb_family:c.orb_family,orb_tier:c.orb_tier,final_build_score:round3(bs),gear_instance_ids:[...gears[ci]],core_score:c.score})}return {status:'PASS',party_score:score,builds,used_instance_ids:gears.flat(),candidate_counts:lists.map(x=>x.length),core_combinations_tested:combos.length}}
function candFromRef(ref){if(ref.startsWith('single:')){const id=ref.slice(7),meta=cat.tables.identities.find(x=>x.name===id),cp=coach.componentPath(cap,id,meta.base_class,12,'primary');return coach.makeCandidate(cap,[cp],12)}const pid=Number(ref.slice(4)),r=cat.profiles[pid],a=cat.tables.identities[r[0]],b=cat.tables.identities[r[1]],c1=coach.componentPath(cap,a.name,a.base_class,r[2],'primary'),c2=coach.componentPath(cap,b.name,b.base_class,r[3],'multiclass');return coach.makeCandidate(cap,[c1,c2],12)}
function paretoFinalists(ci){const d=JSON.parse(fs.readFileSync(`/mnt/data/STEP6B_PRESCORE_GATE_CI${ci}.json`)),rows=d.finalists,dims=['prescore','topcombo_best','proficiency_ratio','need_matches','spell_slot_tiebreak'];const sorted=[...rows].sort((a,b)=>b.prescore-a.prescore||String(a.key).localeCompare(String(b.key))),front=[];function dom(a,b){let strict=false;for(const k of dims){const av=Number(a[k]||0),bv=Number(b[k]||0);if(av<bv-1e-12)return false;if(av>bv+1e-12)strict=true}return strict}for(const x of sorted){if(front.some(y=>dom(y,x)))continue;for(let i=front.length-1;i>=0;i--)if(dom(x,front[i]))front.splice(i,1);front.push(x)}return {gate:d,front:front.sort((a,b)=>b.prescore-a.prescore||b.topcombo_best-a.topcombo_best)} }
function choicesFor(ci,cand){const choices=new Map;for(let i=0;i<4;i++)choices.set(i,coach.currentCandidate(cap,rawSnap.party[i]));if(cand)choices.set(ci,cand);return coach.cloneWithChoices(rawSnap,choices)}
function validateOne(ci,ref){const cand=ref?candFromRef(ref):null,s=choicesFor(ci,cand);console.time('fast');const f=allocateFast(s);console.timeEnd('fast');console.time('orig');const o=solver.allocate(s,data);console.timeEnd('orig');const sameScore=f.party_score===o.party_score,sameBuild=f.builds.every((b,i)=>b.final_build_score===o.builds[i].final_build_score&&JSON.stringify(b.gear_instance_ids)===JSON.stringify(o.builds[i].gear_instance_ids));console.log(JSON.stringify({ci,ref:ref||'current',fast:f.party_score,orig:o.party_score,sameScore,sameBuild,fastBuilds:f.builds.map(x=>x.final_build_score),origBuilds:o.builds.map(x=>x.final_build_score)},null,2));return sameScore&&sameBuild}
async function runAll(){const baseSnap=choicesFor(0,null),baseline=allocateFast(baseSnap);const all={schema:'amp-step6b-current-party-respec-runtime-v2',status:'PASS',baseline_party_score:baseline.party_score,baseline_builds:baseline.builds,characters:[]};for(let ci=0;ci<4;ci++){const {gate,front}=paretoFinalists(ci);const rows=[];console.error('CI',ci,gate.character_name,'front',front.length);for(let j=0;j<front.length;j++){const meta=front[j],cand=candFromRef(meta.ref),s=choicesFor(ci,cand);const r=allocateFast(s);rows.push({...meta,party_score:r.party_score,party_delta:round3(r.party_score-baseline.party_score),char_score:r.builds[ci].final_build_score,char_delta:round3(r.builds[ci].final_build_score-baseline.builds[ci].final_build_score),orb_family:r.builds[ci].orb_family,orb_tier:r.builds[ci].orb_tier,engine_anchor:r.builds[ci].identity,gear_instance_ids:r.builds[ci].gear_instance_ids});console.error(' ',j+1,'/',front.length,meta.label,'=>',r.party_score)}rows.sort((a,b)=>b.party_score-a.party_score||b.char_score-a.char_score||String(a.key).localeCompare(String(b.key)));all.characters.push({character_index:ci,character_name:gate.character_name,current:gate.current,pareto_finalists:front.length,screen_input:gate.input,current_relative_survivors:gate.survivors,results:rows,best:rows[0]||null})}fs.writeFileSync('/mnt/data/STEP6B_CURRENT_PARTY_RESULTS_FAST_EXACT.json',JSON.stringify(all,null,2));console.log(JSON.stringify({baseline:all.baseline_party_score,characters:all.characters.map(x=>({name:x.character_name,finalists:x.pareto_finalists,best:x.best&&{label:x.best.label,party_score:x.best.party_score,party_delta:x.best.party_delta,char_delta:x.best.char_delta,orb:x.best.orb_family}}))},null,2));}
async function runCI(ci){const baseSnap=choicesFor(0,null),baseline=allocateFast(baseSnap),{gate,front}=paretoFinalists(ci),rows=[];console.error('CI',ci,gate.character_name,'front',front.length);for(let j=0;j<front.length;j++){const meta=front[j],cand=candFromRef(meta.ref),s=choicesFor(ci,cand),r=allocateFast(s);rows.push({...meta,party_score:r.party_score,party_delta:round3(r.party_score-baseline.party_score),char_score:r.builds[ci].final_build_score,char_delta:round3(r.builds[ci].final_build_score-baseline.builds[ci].final_build_score),orb_family:r.builds[ci].orb_family,orb_tier:r.builds[ci].orb_tier,engine_anchor:r.builds[ci].identity,gear_instance_ids:r.builds[ci].gear_instance_ids});console.error(' ',j+1,'/',front.length,meta.label,'=>',r.party_score)}rows.sort((a,b)=>b.party_score-a.party_score||b.char_score-a.char_score||String(a.key).localeCompare(String(b.key)));const out={schema:'amp-step6b-current-party-respec-ci-v2',status:'PASS',baseline_party_score:baseline.party_score,baseline_builds:baseline.builds,character_index:ci,character_name:gate.character_name,current:gate.current,pareto_finalists:front.length,screen_input:gate.input,current_relative_survivors:gate.survivors,results:rows,best:rows[0]||null};const path=`/mnt/data/STEP6B_CURRENT_PARTY_CI${ci}.json`;fs.writeFileSync(path,JSON.stringify(out,null,2));console.log(JSON.stringify({path,name:out.character_name,baseline:out.baseline_party_score,finalists:out.pareto_finalists,best:out.best&&{label:out.best.label,party_score:out.best.party_score,party_delta:out.best.party_delta,char_delta:out.best.char_delta,orb:out.best.orb_family}},null,2));}
const cmd=process.argv[2]||'run';if(cmd==='validate')validateOne(Number(process.argv[3]||0),process.argv[4]||null);else if(cmd==='run')runAll();else if(cmd==='run-ci')runCI(Number(process.argv[3]||0));else if(cmd==='fast-one'){const ci=Number(process.argv[3]||0),ref=process.argv[4]||null,c=ref?candFromRef(ref):null,ss=choicesFor(ci,c);console.time('fast-one');const r=allocateFast(ss);console.timeEnd('fast-one');console.log(JSON.stringify({ci,ref:ref||'current',party_score:r.party_score,builds:r.builds},null,2));}else if(cmd==='fast-one-file'){const ci=Number(process.argv[3]||0),ref=process.argv[4]||null,outf=process.argv[5],c=ref?candFromRef(ref):null,ss=choicesFor(ci,c),r=allocateFast(ss);fs.writeFileSync(outf,JSON.stringify({ci,ref:ref||'current',party_score:r.party_score,builds:r.builds}));console.log(outf,r.party_score);}else if(cmd==='joint'){const spec=process.argv[3]||'',choices=new Map;for(let i=0;i<4;i++)choices.set(i,coach.currentCandidate(cap,rawSnap.party[i]));for(const part of spec.split(',').filter(Boolean)){const [i,ref]=part.split('=');choices.set(Number(i),candFromRef(ref));}const ss=coach.cloneWithChoices(rawSnap,choices);console.time('fast');const f=allocateFast(ss);console.timeEnd('fast');console.time('orig');const o=solver.allocate(ss,data);console.timeEnd('orig');console.log(JSON.stringify({spec,fast:f.party_score,orig:o.party_score,sameScore:f.party_score===o.party_score,sameBuild:f.builds.every((b,i)=>b.final_build_score===o.builds[i].final_build_score&&JSON.stringify(b.gear_instance_ids)===JSON.stringify(o.builds[i].gear_instance_ids)),builds:o.builds.map(x=>({name:x.character_name,identity:x.identity,orb:x.orb_family,score:x.final_build_score,gear:x.gear_instance_ids}))},null,2));}else if(cmd==='vary-joint-file'){const ci=Number(process.argv[3]||0),fixed=process.argv[4]||'',ref=process.argv[5],outf=process.argv[6],choices=new Map;for(let i=0;i<4;i++)choices.set(i,coach.currentCandidate(cap,rawSnap.party[i]));for(const part of fixed.split(',').filter(Boolean)){const [i,r]=part.split('=');choices.set(Number(i),candFromRef(r));}choices.set(ci,candFromRef(ref));const ss=coach.cloneWithChoices(rawSnap,choices),r=allocateFast(ss);fs.writeFileSync(outf,JSON.stringify({ci,fixed,ref,party_score:r.party_score,builds:r.builds}));console.log(outf,r.party_score);}else if(cmd==='pareto'){for(let ci=0;ci<4;ci++){const z=paretoFinalists(ci);console.log(ci,z.gate.character_name,z.front.length,z.front.map(x=>x.label))}}
